---
title: 'Reliability, Maintainability, and Quality Management'
subtitle: 'LOGM 634 (ASAM - 2018)'
output: 
  pdf_document:
    keep_tex: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
\pagenumbering{gobble}

## Instructor

Maj Jason K. Freels, PhD 	<jason.freels@us.af.mil>\newline\newline
AFIT/ENV\newline
2950 Hobson Way\newline
WPAFB, OH 45433-7765\newline
Cell:  937.430.6619\newline
Work:  937.255.3636 ext 4676	  	
			
## Course Text

- Ebeling, C., <u>__An Introduction to Reliability and Maintainability Engineering__</u>, 2nd Ed., Waveland Press, 2010

## Additional References (Optional)

- O'Connor, P. & Kleyner, A., <u>__Practical Reliability Engineering__</u>, 5th Ed., Wiley, 2012

- Meeker, W. & Escobar, L., <u>__Statistical Methods for Reliability Data__</u>, 1st Ed., Wiley, 1998

- Rausand, M. & Hoyland, A., <u>__Systems Reliability Theory – Statistical Methods and Applications__</u>, 2nd Ed., Wiley, 2003

- DOD Guide for Achieving Reliability, Availability, and Maintainability, 3 Aug 2005

## Course Description

Creating and sustaining military capability is the purpose of military leadership and management. Reliability and maintainability (R&M) are component characteristics, which define the ability of a product to perform its specified functions throughout its operational life. Component R&M of the military system are primary determinants of military capability. This course teaches fundamental R&M concepts. Additionally, probability theory is discussed and employed as a tool to quantitatively define these concepts. Topics to be discussed include the measures, which quantitatively define component R&M, the relationship between R&M, and the prediction of R&M measures.  

## Course Objectives

Upon completion of this course each student shall be able to:

-	Understand and apply the fundamentals of the concepts of reliability, maintainability, and availability.

- Understand the use of probability theory to quantify R&M concepts.

- Understand and apply the measures which quantitatively define component R&M.
 
## Academic Integrity

Students found to be cheating will be referred for disciplinary action.  Cheating includes, but is not limited to, copying on exams, plagiarizing material from published sources, plagiarizing from former or current AFIT students, submitting someone else’s work as your own, or helping other students to cheat.  If you have any questions regarding what is permissible, please contact the professor for guidance.

## Course Format

Class material is primarily presented in lecture format.

## Performance Evaluation

Your grade in this course will be calculated according to the following requirements and their respective weights.

- __HOMEWORK (40\%):__\newline Homework is due at the beginning of class on the day listed in the class schedule.  Each student must turn in their own solutions for each problem assigned - Unless other arrangements are approved by the instructor.  Solutions will be posted that evening.

- __PROJECT (30\%):__  \newline Students, in teams of two, will prepare a class presentation on a topic relevant to reliability, maintainability, and availability.  Presentations should be about 20 minutes long.  Students may choose a relevant DoD topic or their own topic, approved by the professor.  Topics and teams are "first-come, first-served"  Topic presentations will include the topic's background and why it is important or relevant, a brief literature review of the research on this topic, a description and assessment of any quantitative reliability tools used, and a managerial assessment of why USAF leaders should know and care about it.  

> Project examples: Evaluation of the C-5 re-engining and reliability improvement program, a B-52 life extension program, F-35 software reliability, GM ignition switch failures,r automotive air bag failures, the Samsung Galaxy Note 7 failures, or electric car battery failures.

- __FINAL EXAM (30\%):__  \newline The final exam will test comprehension of the course material in the book and class presentations, and ability to analytically solve problems scoped similar to the homework.  The exam is closed book, closed notes.  Students may prepare a formula sheet, on 8 ½" x 11" paper, and use both the front and back.  Students will have two hours to finish the exam.
 
Your final grade in this course will be based on the following scale:

\begin{tabbing}
\=\hspace{200pt}93\%\quad \=$-$\quad \=100\%\quad\=  A \\
\>\hspace{200pt}90\%\quad \>$-$\quad \>92\% \quad\>  A-\\
\>\hspace{200pt}87\%\quad \>$-$\quad \>89\% \quad\>  B+\\
\>\hspace{200pt}83\%\quad \>$-$\quad \>86\% \quad\>  B \\
\>\hspace{200pt}80\%\quad \>$-$\quad \>82\% \quad\>  B-\\
\>\hspace{200pt}77\%\quad \>$-$\quad \>79\% \quad\>  C+\\
\>\hspace{200pt}73\%\quad \>$-$\quad \>76\% \quad\>  C \\
\>\hspace{200pt}70\%\quad \>$-$\quad \>72\% \quad\>  C-\\
\>       \><\quad \>70\%\quad \> D or F
\end{tabbing}

\newpage

## Class Schedule

\begin{tabbing}
\textbf{Class Date}\hspace{20pt}  \=\textbf{Chapters Covered}\hspace{20pt} \=\textbf{Topics}\hspace{120pt} \=\textbf{Notes}\\
\rule{\textwidth}{0.5pt}\\[5pt]
Day 1 \> Chapters 1 \& 2     \> Course Overview                 \>HW \#1 Assigned\\
      \>                     \> Reliability Introduction        \>\\
      \>                     \> Math Review                     \>\\
\rule{\textwidth}{0.5pt}\\[5pt]
Day 2 \> Chapters 3, 4       \> Failure Models                  \>\\
\rule{\textwidth}{0.5pt}\\[5pt]
Day 3 \> Chapters 4, 5       \> Failure Models                  \>HW \#1 Due\\
      \>                     \> System Reliability              \>HW \#2 Assigned\\
\rule{\textwidth}{0.5pt}\\[5pt]
Day 4 \> Chapters 6, 7       \> State Dependent Systems         \>\\
      \>                     \> Physical Reliability Models     \>\\
\rule{\textwidth}{0.5pt}\\[5pt]
Day 5 \> Chapters 7, 8       \> Physical Reliability Models     \>HW \#2 Due\\
      \>                     \> Design for Reliability          \>HW \#3 Assigned\\
      \>                     \> Reliability Growth Testing      \>Project Topics Due\\
\rule{\textwidth}{0.5pt}\\[5pt]
Day 6 \> N/A                 \> MLK Day                         \>\\
\rule{\textwidth}{0.5pt}\\[5pt]
Day 7 \> Chapters 7, 8       \> Design for Reliability          \>HW \#3 Due\\
      \>                     \> Reliability Growth Testing      \>HW \#4 Assigned\\
\rule{\textwidth}{0.5pt}\\[5pt]
Day 8 \> Chapters 9, 10      \> Maintainability                 \>\\
      \>                     \> Design for Maintainability      \>\\
\rule{\textwidth}{0.5pt}\\[5pt]
Day 9 \> Chapters 15, 16, 17 \> Reliability in Manufacture      \>HW \#4 Due\\
      \>                     \> Maintainability \& Availability \>Review For Final\\
      \>                     \> Reliability Management          \>\\
\rule{\textwidth}{0.5pt}\\[5pt]
Day 10\> N/A                 \>N/A                              \>Student Presentations\\
      \>                     \>                                 \>Final Exam\\
\rule{\textwidth}{0.5pt}\\[5pt]
\end{tabbing}

## Useful Reliabilty Websites

\begin{tabbing}
University of Tennessee, Knoxville - Reliability and Maintainability Center\quad\quad \= \href{http://www.rmc.utk.edu/}{(LINK)}\\[5pt]
The Reliability Information Analysis Center \> \href{https://www.quanterion.com/projects/reliability-information-analysis-center-riac/}{(LINK)}\\[5pt]

Government-Industry Data Exchange Program \> \href{http://www.gidep.org/}{(LINK)}\\[5pt]

The American Society for Quality\> \href{http://www.asq.org/index.html}{(LINK)}\\[5pt]

Weibull.com \> \href{http://www.weibull.com/knowledge/links.htm}{(LINK)}\\[5pt]

University of Maryland Reliability Engineering\> \href{http://www.enre.umd.edu/}{(LINK)}\\[5pt]
\end{tabbing}
